# Generated by Django 4.2.1 on 2023-05-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedOneWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightType', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departureDate', models.DateTimeField(max_length=200)),
                ('totalAmount', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookedRoundTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightType', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departureDate', models.DateTimeField(max_length=200)),
                ('returnDate', models.DateTimeField(max_length=200)),
                ('totalAmount', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OneWayFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightType', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departureDate', models.DateTimeField(max_length=200)),
                ('totalAmount', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoundTripFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightType', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departureDate', models.DateTimeField(max_length=200)),
                ('returnDate', models.DateTimeField(max_length=200)),
                ('totalAmount', models.CharField(max_length=200)),
            ],
        ),
    ]
