# Generated by Django 4.2.1 on 2023-05-31 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedoneway',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedroundtrip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookedoneway',
            name='departureDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='departureDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookedroundtrip',
            name='returnDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='onewayflight',
            name='departureDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='departureDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roundtripflight',
            name='returnDate',
            field=models.DateField(),
        ),
    ]
